### ISSUE TITLE
remove liquidity page improvements

### ISSUE THREAD

**Issue by Thykof** [dusaprotocol/docs#3]
here https://docs.dusa.io/SDK/removeLiquidity

Variables not defined:
- deadline
- pairAddress

typos:
- currenTimeInMs => currentTimeInMs
- slipage => slippage

**Comment by JoeTheCookie217** [comment]
Thx for the review

Fixed in a3657cbf12ab498f939a0424395007f9dbbb6a40

**Comment by Thykof** [comment]
You're welcome ;)
